# Exchange-Traded Funds — Indonesia

> **Educational research universe—not a buy list.** Inclusion only means an instrument is useful to study. Before investing, verify current availability, legal documents, price/NAV, fees, liquidity, tax, risks, and whether it fits your goals and loss capacity. Names and classifications can change. Starter lists last reviewed: **2026-09-18**.

An ETF can track an index reasonably while still being costly to trade if its bid–ask spread or market depth is poor.

In [1]:
import pandas as pd

universe = pd.DataFrame([
  {
    "ticker": "R-LQ45X",
    "name": "Premier ETF LQ-45",
    "exposure_to_verify": "LQ45 equity index",
    "research_first": "Spread, on-screen depth, NAV discount/premium, tracking difference"
  },
  {
    "ticker": "XIIT",
    "name": "Premier ETF IDX30",
    "exposure_to_verify": "IDX30 equity index",
    "research_first": "Spread, liquidity, concentration, tracking difference"
  },
  {
    "ticker": "XMLF",
    "name": "Mandiri ETF LQ45",
    "exposure_to_verify": "LQ45 equity index",
    "research_first": "Spread, liquidity, NAV, fees"
  },
  {
    "ticker": "XCLQ",
    "name": "Cipta ETF Index LQ45",
    "exposure_to_verify": "LQ45 equity index",
    "research_first": "Spread, liquidity, NAV, fees"
  },
  {
    "ticker": "XIID",
    "name": "Premier ETF Index IDX30",
    "exposure_to_verify": "IDX30 equity index",
    "research_first": "Spread, liquidity, tracking difference, fees"
  },
  {
    "ticker": "XMGB",
    "name": "Majoris Government Bonds ETF Indonesia",
    "exposure_to_verify": "Government bonds",
    "research_first": "Duration, yield, spread, NAV, interest-rate sensitivity"
  },
  {
    "ticker": "XMSK",
    "name": "Mandiri ETF SRI-KEHATI",
    "exposure_to_verify": "SRI-KEHATI equity index",
    "research_first": "Index methodology, concentration, spread, tracking"
  },
  {
    "ticker": "XPDV",
    "name": "Pinnacle Core High Dividend ETF",
    "exposure_to_verify": "Dividend-oriented equities",
    "research_first": "Index rules, dividend traps, sector concentration, spread"
  }
])
universe

,ticker,name,exposure_to_verify,research_first
0,R-LQ45X,Premier ETF LQ-45,LQ45 equity index,"Spread, on-screen depth, NAV discount/premium,..."
1,XIIT,Premier ETF IDX30,IDX30 equity index,"Spread, liquidity, concentration, tracking dif..."
2,XMLF,Mandiri ETF LQ45,LQ45 equity index,"Spread, liquidity, NAV, fees"
3,XCLQ,Cipta ETF Index LQ45,LQ45 equity index,"Spread, liquidity, NAV, fees"
4,XIID,Premier ETF Index IDX30,IDX30 equity index,"Spread, liquidity, tracking difference, fees"
5,XMGB,Majoris Government Bonds ETF Indonesia,Government bonds,"Duration, yield, spread, NAV, interest-rate se..."
6,XMSK,Mandiri ETF SRI-KEHATI,SRI-KEHATI equity index,"Index methodology, concentration, spread, trac..."
7,XPDV,Pinnacle Core High Dividend ETF,Dividend-oriented equities,"Index rules, dividend traps, sector concentrat..."

In [2]:
equity_like = universe[universe['exposure_to_verify'].str.contains('equity|IDX|LQ45|SRI', case=False, regex=True)]
equity_like[['ticker', 'name', 'exposure_to_verify']]

    ticker                     name       exposure_to_verify
0  R-LQ45X        Premier ETF LQ-45        LQ45 equity index
1     XIIT        Premier ETF IDX30       IDX30 equity index
2     XMLF         Mandiri ETF LQ45        LQ45 equity index
3     XCLQ     Cipta ETF Index LQ45        LQ45 equity index
4     XIID  Premier ETF Index IDX30       IDX30 equity index
6     XMSK   Mandiri ETF SRI-KEHATI  SRI-KEHATI equity index

## Minimum pre-trade study

Record exchange status, latest prospectus, index methodology, AUM, management fee, tracking difference, indicative NAV if available, bid, ask, spread percentage, depth at several levels, normal daily traded value, creation-unit mechanism, and tax/fees. Observe several trading days; a one-minute snapshot is weak evidence.

## Primary sources

- [KSEI mutual-fund/ETF register](https://web.ksei.co.id/services/registered-securities/mutual-funds?setLocale=id-ID)
- [IDX market data](https://www.idx.co.id/id/data-pasar/)
- The ETF prospectus, fund fact sheet, and index provider methodology